// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";

// F1.2: "A generated verifier SHALL verify a real proof on the local chain,
// and reject a tampered one." Fixtures below are a real proof generated by
// the poseidon-baseline circuit (circuits/poseidon-baseline/{proof,public}.json)
// for input {"in": ["1", "2"]}, exported via
// `snarkjs zkey export soliditycalldata public.json proof.json`.
contract Groth16VerifierTest is Test {
    Groth16Verifier internal verifier;

    uint256[2] internal pA;
    uint256[2][2] internal pB;
    uint256[2] internal pC;
    // Poseidon(1, 2) - the canonical circomlib test vector
    uint256[1] internal pubSignals;

    function setUp() public {
        verifier = new Groth16Verifier();

        pA[0] = 0x2655b05c458d1bbe9699c544abefb7078da913321fac68faaf46248a308c13e5;
        pA[1] = 0x271d1e744176ddd4252c68af022953e2f686af15fb547eba0a091bc04c4b8867;

        pB[0][0] = 0x28a8b83a77a08f722f6786d31bb54465740207e786708787cf2157fa97afb26f;
        pB[0][1] = 0x0b27e916bc1db95727bf375967fed141bf318d3bb1d7c566434c46f07ae8259a;
        pB[1][0] = 0x00af2da5dbdfa171bcfcd3c177a5c0fd4815759e97fde046c0869f6f5b209f4d;
        pB[1][1] = 0x17d950bcb4c72e61e60b56cf29b2bb1a914542122999aa00ec786802dcb0c02c;

        pC[0] = 0x28cb352f51a2e9681f16d5dfabf201021a5ff92e01f79a620c5da3a287877fbc;
        pC[1] = 0x0c0be64b806261a43d3c7852ae8638e46aebf4b2b59e1baa30cb236a46afd8e4;

        pubSignals[0] = 0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a;
    }

    function test_GenuineProofVerifies() public view {
        bool ok = verifier.verifyProof(pA, pB, pC, pubSignals);
        assertTrue(ok, "genuine proof should verify");
    }

    function test_TamperedProofRejected() public view {
        uint256[2] memory tamperedA = pA;
        tamperedA[0] = tamperedA[0] + 1;
        bool ok = verifier.verifyProof(tamperedA, pB, pC, pubSignals);
        assertFalse(ok, "tampered proof.A should not verify");
    }

    function test_TamperedPublicInputRejected() public view {
        uint256[1] memory tamperedSignals = pubSignals;
        tamperedSignals[0] = tamperedSignals[0] + 1;
        bool ok = verifier.verifyProof(pA, pB, pC, tamperedSignals);
        assertFalse(ok, "tampered public input should not verify");
    }
}
