// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";

// F1.2: "A generated verifier SHALL verify a real proof on the local chain,
// and reject a tampered one." Fixtures below are a real proof generated by
// the poseidon-baseline circuit (circuits/poseidon-baseline/{proof,public}.json)
// for input {"in": ["1", "2"]}, exported via
// `snarkjs zkey export soliditycalldata public.json proof.json`.
contract Groth16VerifierTest is Test {
    Groth16Verifier internal verifier;

    uint256[2] internal pA;
    uint256[2][2] internal pB;
    uint256[2] internal pC;
    // Poseidon(1, 2) - the canonical circomlib test vector
    uint256[1] internal pubSignals;

    function setUp() public {
        verifier = new Groth16Verifier();

        pA[0] = 0x299a5627c02725456485a9a7c4e1399bb15f588dceb481201428c9f65c8693c3;
        pA[1] = 0x2702b8ff8d1833dddd92fe0c3998b9fa493337b21cdc3b6a6987d7d06dc95b07;

        pB[0][0] = 0x251f0ed6989b657ffffaee817f81e588713910a861970b4b96e65d316688c10a;
        pB[0][1] = 0x1bdf1aafb28a0e903efac8d4218ccb1c56a362048085ee9df0996db053c3822a;
        pB[1][0] = 0x041aacbd3a49f20e5606d67297d724ffd07098d2372597594bd632658c1a3646;
        pB[1][1] = 0x0599f2df9fb7dcde0b480d5b260eb328d7ffdb93be8d9ed86b3549b109544a8c;

        pC[0] = 0x18ec9c78c2675f65610eeb5d4269f808b9caf7a12660a3a760a956aaf7fd25d3;
        pC[1] = 0x06e49dc4448b0b6dfa72e09b5efc3d69435f862da8cb7138ba3794d7eb3e00cc;

        pubSignals[0] = 0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a;
    }

    function test_GenuineProofVerifies() public view {
        bool ok = verifier.verifyProof(pA, pB, pC, pubSignals);
        assertTrue(ok, "genuine proof should verify");
    }

    function test_TamperedProofRejected() public view {
        uint256[2] memory tamperedA = pA;
        tamperedA[0] = tamperedA[0] + 1;
        bool ok = verifier.verifyProof(tamperedA, pB, pC, pubSignals);
        assertFalse(ok, "tampered proof.A should not verify");
    }

    function test_TamperedPublicInputRejected() public view {
        uint256[1] memory tamperedSignals = pubSignals;
        tamperedSignals[0] = tamperedSignals[0] + 1;
        bool ok = verifier.verifyProof(pA, pB, pC, tamperedSignals);
        assertFalse(ok, "tampered public input should not verify");
    }
}
